version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  install:
    docker:
      - image: cimg/node:17.0.1
    steps:
      - node/install:
          install-npm: false
          install-yarn: true
      - node/install-packages:
          app-dir: .
          pkg-manager: yarn

workflows:
  example-workflow:
    jobs:
      - install
