version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
      - node/install-npm
      - node/install-packages:
          app-dir: .
          pkg-manager: yarn
          with-cache: false
      - run:
          name: Build app
          command: yarn build

workflows:
  node_build:
    jobs:
      - build
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
