version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  example-job:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true
          install-npm: false
workflows:
  example-workflow:
    jobs:
      - example-job
