version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
      - node/install-npm
      - node/install-packages:
          app-dir: .
          pkg-manager: yarn
          with-cache: false
      - run: npx lerna publish patch --yes

workflows:
  build-workflow:
    jobs:
      - build
