version: 2.1

jobs:
  install:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run
        name: Install npm dependencies
        command: |
          yarn
workflows:
  build_install:
    jobs:
      - install
